POST http://localhost:3000/api/comments
Content-Type: application/json

{
    "user": "6526604f94f808905330ba33",
    "entry": "6527e3936871c0a035f89e69",
    "body": "This is a comment about a comment"
}