GET http://localhost:3000/api/entries


###
GET http://localhost:3000/api/entries/6532d9d57e3f55fba38bd760


###
POST http://localhost:3000/api/entries/create
Content-Type: application/json

{
    "title": "Look at this stuff",
    "description": "it's a funny story",
    "body": "Wouldnt you think Im a girl, a girl who has, evertything",
    "user": "652666c4559f8216cdb756f1",
    "categories": "652509e897a9c2ea6fae0d97",
    "language": "652699b2bf0592c9c21686ff",
    "content_rating": "6532d07fbdbbebce9d4ba147"
}

###
DELETE http://localhost:3000/api/entries/652d1aa90936e0b06a783ff3