POST http://localhost:3000/api/entries
Content-Type: application/json

{
    "title": "This is a story about a girl Named Lucky",
    "excerpt": "Early morning, she wakes up and it knocks knocks knocks on the door",
    "body": "Its time for makeup, a perfect smile, but theres no one there to wake her up",
    "author": "652666c4559f8216cdb756f1",
    "categories": "652509e897a9c2ea6fae0d97",
    "language": "652699b2bf0592c9c21686ff"
}